export interface IInstitution {
    institutionId?: number | null | undefined;
    institutionName?: string | null | undefined
    organizationId?: number | null | undefined;
    selectedOrganization?: any | null | undefined
    name?: string | null | undefined;
    shortName?: string | null | undefined;
    UDISECode?: string | null | undefined;
    //
    stateId?: number | null | undefined;
    selectedState?: any | null | undefined
    city?: string | null | undefined;
    block?: string | null | undefined;
    locationId?: number | null | undefined;
    selectedLocation?: any | null | undefined
    cluster?: string | null | undefined;
    ward?: string | null | undefined;
    mohalla?: string | null | undefined;
    pinCode?: number | null | undefined;
    panchayat?: string | null | undefined;
    municipality?: string | null | undefined;
    categoryId?: number | null | undefined;
    selectedCategory?: any | null | undefined;
    stateManagementId?: number | null | undefined;
    stateManagement?: any | null | undefined;
    nationalManagementId?: number | null | undefined;
    nationalManagement?: any | null | undefined;
    typeId?: number | null | undefined;
    selectedSchoolType?: any | null | undefined;
    classFrom?: number | null | undefined;
    classTo?: number | null | undefined;
    isPrePrimary?: boolean | null | undefined;
    selectedPrePrimary?: any | null | undefined;
    mediumId?: boolean | null | undefined;
    selectedMedium?: any | null | undefined;
    selectedBoard?: any | null | undefined;
    //
    regAddress1?: string | null | undefined;
    regAddress2?: string | null | undefined;
    regAddress3?: string | null | undefined;
    regAddress4?: string | null | undefined;
    regCity?: string | null | undefined;
    regStateId?: number | null | undefined;
    regSelectedState?: any | null | undefined;
    regCountryId?: number | null | undefined;
    regSelectedCountry?: any | null | undefined;
    regPINCode?: number | null | undefined;
    mobileNumber1?: string | null | undefined;
    mobileNumber2?: string | null | undefined;
    phoneNumber1?: string | null | undefined;
    phoneNumber2?: string | null | undefined;
    fax?: string | null | undefined;
    primaryEmail?: string | null | undefined;
    secondaryEmail?: string | null | undefined;
    website?: string | null | undefined;
    //
    yearofEstablishment?: number | null | undefined;
    yearofRecognition_Primary?: number | null | undefined;
    yearofRecognition_UpperPrimary?: number | null | undefined;
    yearofRecognition_Secondary?: number | null | undefined;
    yearofRecognition_HigherSecondary?: number | null | undefined;
    affiliationBoard_Secondary?: number | null | undefined;
    affiliationBoard_HigherSecondary?: number | null | undefined;
    isMinoritySchool?: boolean | null | undefined;
    selectedMinoritySchool?: any | null | undefined;
    isthisaShiftSchool?: boolean | null | undefined;
    selectedIsthisaShiftSchool?: any | null | undefined;
    buildingStatusId?: number | null | undefined;
    selectedBuildingStatus?: any | null | undefined;
    boundaryWallId?: number | null | undefined;
    selectedBoundaryWall?: any | null | undefined;
    noofBuildingBlocks?: number | null | undefined;
    noofPuccaBuildingBlocks?: number | null | undefined;
    isSpecialSchoolforCWSN?: boolean | null | undefined;
    selectedIsSpecialSchoolforCWSN?: any | null | undefined;
    availabilityofRamps?: boolean | null | undefined;
    selectedAvailabilityofRamps?: any | null | undefined;
    availabilityofHandrails?: boolean | null | undefined;
    selectedAvailabilityofHandrails?: any | null | undefined;
    totalNoOfToilets_Boys?: number | null | undefined;
    totalNoOfToilets_Girls?: number | null | undefined;
    functional_Boys?: number | null | undefined;
    functional_Girls?: number | null | undefined;
    functionalCWSNFriendly_Boys?: number | null | undefined;
    functionalCWSNFriendly_Girls?: number | null | undefined;
    urinal_Boys?: number | null | undefined;
    urinal_Girls?: number | null | undefined;
    handwashNearToilet?: boolean | null | undefined;
    selectedHandwashNearToilet?: any | null | undefined;
    handwashFacilityforMeal?: boolean | null | undefined;
    selectedHandwashFacilityforMeal?: any | null | undefined;
    drinkingWaterAvailable?: boolean | null | undefined;
    selectedDrinkingWaterAvailable?: any | null | undefined;
    drinkingWaterFunctional?: boolean | null | undefined;
    selectedDrinkingWaterFunctional?: any | null | undefined;
    rainWaterHarvesting?: boolean | null | undefined;
    selectedRainWaterHarvesting?: any | null | undefined;
    playgroundAvailable?: boolean | null | undefined;
    selectedPlaygroundAvailable?: any | null | undefined;
    noofBuildingsInGoodCondition?: number | null | undefined;
    noofBuildingNeedsMinorRepair?: number | null | undefined;
    noofBuildingNeedsMajorRepair?: number | null | undefined;
    otherRooms?: number | null | undefined;
    libraryAvailability?: boolean | null | undefined;
    selectedLibraryAvailability?: any | null | undefined;
    separateRoomforHM?: boolean | null | undefined;
    selectedSeparateRoomforHM?: any | null | undefined;
    furnitureAvailability?: boolean | null | undefined;
    selectedFurnitureAvailability?: any | null | undefined;
    electricityAvailability?: boolean | null | undefined;
    selectedElectricityAvailability?: any | null | undefined;
    solarPanel?: boolean | null | undefined;
    selectedSolarPanel?: any | null | undefined;
    medicalcheckups?: boolean | null | undefined;
    selectedMedicalcheckups?: any | null | undefined;
    //
    iCTLab?: boolean | null | undefined;
    selectedICTLab?: any | null | undefined;
    internetConnection?: boolean | null | undefined;
    selectedInternetConnection?: any | null | undefined;
    dTHConnection?: boolean | null | undefined;
    selectedDTHConnection?: any | null | undefined;
    noofDesktop?: number | null | undefined;
    noofLaptop?: number | null | undefined;
    noofTablet?: number | null | undefined;
    noofPrinter?: number | null | undefined;
    noofProjector?: number | null | undefined;
    noofDigiBoard?: number | null | undefined;
    //
    noofTeachers_Primary?: number | null | undefined;
    noofTeachers_PrimaryandUpperPrimary?: number | null | undefined;
    noofTeachers_HigerSecondaryOnly?: number | null | undefined;
    noofTeachers_SecondaryandHigerSecondary?: number | null | undefined;
    noofTeachers_PrePrimaryandPrimary?: number | null | undefined;
    noofTeachers_UpperPrimary?: number | null | undefined;
    noofTeachers_SecondaryOnly?: number | null | undefined;
    noofTeachers_UpperPrimaryandSecondary?: number | null | undefined;
    noofTeachers_PrePrimaryOnly?: number | null | undefined;
    noofTeachers_Regular?: number | null | undefined;
    noofTeachers_Parttime?: number | null | undefined;
    noofTeachers_Contract?: number | null | undefined;
    noofTeachers_Male?: number | null | undefined;
    noofTeachers_Female?: number | null | undefined;
    noofTeachers_Transgender?: number | null | undefined;
    totalNoofTeachers?: number | null | undefined;
    noofTotalTeacherReceivedServiceTraining?: number | null | undefined;
    totalTeacherInvolveinNonTeachingAssignment?: number | null | undefined;
    noofTeachers_BelowGraduate?: number | null | undefined;
    noofTeachers_Graduate?: number | null | undefined;
    noofTeachers_PostGraduateandAbove?: number | null | undefined;
    noofTotalTeachersTrainedinComputer?: number | null | undefined;
    noofTeachers_AgedAbove55?: number | null | undefined;
    noofTeachers_DiplomaorCertificateinbasicteacherstraining?: number | null | undefined;
    noofTeachers_BachelorofElementaryEducation?: number | null | undefined;
    noofTeachers_BEdorEquivalent?: number | null | undefined;
    noofTeachers_MEdorEquivalent?: number | null | undefined;
    noofTeachers_DiplomaorDegreeinSpecialEducation?: number | null | undefined;
    noofTeachers_PursuinganyRelevantProfessionalCourse?: number | null | undefined;
    //
    isActive?: boolean | null | undefined;
    userId?: number | null | undefined;
    ipAddress?: string | null | undefined;

}





