export interface IInstitution {
    institutionId?: number | null | undefined;
    institutionName?: string | null | undefined
    organizationId?: number | null | undefined;
    selectedOrganization?: any | null | undefined
    name?: string | null | undefined;
    shortName?: string | null | undefined;
    udiseCode?: string | null | undefined;
    //
    stateId?: number | null | undefined;
    selectedState?: any | null | undefined
    city?: string | null | undefined;
    block?: string | null | undefined;
    locationId?: number | null | undefined;
    selectedLocation?: any | null | undefined
    cluster?: string | null | undefined;
    ward?: string | null | undefined;
    mahalla?: string | null | undefined;
    pinCode?: number | null | undefined;
    panchayat?: string | null | undefined;
    municipality?: string | null | undefined;
    schoolCategoryId?: number | null | undefined;
    selectedCategory?: any | null | undefined;
    stateManagementId?: number | null | undefined;
    stateManagement?: any | null | undefined;
    nationalManagementId?: number | null | undefined;
    nationalManagement?: any | null | undefined;
    schoolTypeId?: number | null | undefined;
    selectedSchoolType?: any | null | undefined;
    classFrom?: number | null | undefined;
    classTo?: number | null | undefined;
    isPrePrimary?: boolean | null | undefined;
    selectedPrePrimary?: any | null | undefined;
    instructionId?: boolean | null | undefined;
    selectedMedium?: any | null | undefined;
    selectedBoard?: any | null | undefined;
    //
    regAddress1?: string | null | undefined;
    regAddress2?: string | null | undefined;
    regAddress3?: string | null | undefined;
    regAddress4?: string | null | undefined;
    regCity?: string | null | undefined;
    regStateId?: number | null | undefined;
    regSelectedState?: any | null | undefined;
    regCountryId?: number | null | undefined;
    regSelectedCountry?: any | null | undefined;
    regPINCode?: number | null | undefined;
    mobileNumber1?: string | null | undefined;
    mobileNumber2?: string | null | undefined;
    phoneNumber1?: string | null | undefined;
    phoneNumber2?: string | null | undefined;
    fax?: string | null | undefined;
    primaryEmail?: string | null | undefined;
    secondaryEmail?: string | null | undefined;
    website?: string | null | undefined;
    //
    yearofEstablishment?: number | null | undefined;
    yearofRecognitionPrimary?: number | null | undefined;
    yearofRecognitionUpperPrimary?: number | null | undefined;
    yearofRecognitionSecondary?: number | null | undefined;
    yearofRecognitionHigherSecondary?: number | null | undefined;
    affiliationBoardSecondary?: number | null | undefined;
    affiliationBoardHigherSecondary?: number | null | undefined;
    isMinoritySchool?: boolean | null | undefined;
    selectedMinoritySchool?: any | null | undefined;
    isthisaShiftSchool?: boolean | null | undefined;
    selectedIsthisaShiftSchool?: any | null | undefined;
    buildingStatusId?: number | null | undefined;
    selectedBuildingStatus?: any | null | undefined;
    boundaryWallId?: number | null | undefined;
    selectedBoundaryWall?: any | null | undefined;
    noofBuildingBlocks?: number | null | undefined;
    noofPuccaBuildingBlocks?: number | null | undefined;
    isSpecialSchoolforCWSN?: boolean | null | undefined;
    selectedIsSpecialSchoolforCWSN?: any | null | undefined;
    availabilityofRamps?: boolean | null | undefined;
    selectedAvailabilityofRamps?: any | null | undefined;
    availabilityofHandrails?: boolean | null | undefined;
    selectedAvailabilityofHandrails?: any | null | undefined;
    totalNoOfToiletsBoys?: number | null | undefined;
    totalNoOfToiletsGirls?: number | null | undefined;
    functionalBoys?: number | null | undefined;
    functionalGirls?: number | null | undefined;
    functionalCWSNFriendlyBoys?: number | null | undefined;
    functionalCWSNFriendlyGirls?: number | null | undefined;
    urinalBoys?: number | null | undefined;
    urinalGirls?: number | null | undefined;
    handwashNearToilet?: boolean | null | undefined;
    selectedHandwashNearToilet?: any | null | undefined;
    handwashFacilityforMeal?: boolean | null | undefined;
    selectedHandwashFacilityforMeal?: any | null | undefined;
    drinkingWaterAvailable?: boolean | null | undefined;
    selectedDrinkingWaterAvailable?: any | null | undefined;
    drinkingWaterFunctional?: boolean | null | undefined;
    selectedDrinkingWaterFunctional?: any | null | undefined;
    rainWaterHarvesting?: boolean | null | undefined;
    selectedRainWaterHarvesting?: any | null | undefined;
    playgroundAvailable?: boolean | null | undefined;
    selectedPlaygroundAvailable?: any | null | undefined;
    noofBuildingsInGoodCondition?: number | null | undefined;
    noofBuildingNeedsMinorRepair?: number | null | undefined;
    noofBuildingNeedsMajorRepair?: number | null | undefined;
    otherRooms?: number | null | undefined;
    libraryAvailability?: boolean | null | undefined;
    selectedLibraryAvailability?: any | null | undefined;
    separateRoomforHM?: boolean | null | undefined;
    selectedSeparateRoomforHM?: any | null | undefined;
    furnitureAvailability?: boolean | null | undefined;
    selectedFurnitureAvailability?: any | null | undefined;
    electricityAvailability?: boolean | null | undefined;
    selectedElectricityAvailability?: any | null | undefined;
    solarPanel?: boolean | null | undefined;
    selectedSolarPanel?: any | null | undefined;
    medicalcheckups?: boolean | null | undefined;
    selectedMedicalcheckups?: any | null | undefined;
    //
    ictLab?: boolean | null | undefined;
    selectedICTLab?: any | null | undefined;
    internetConnection?: boolean | null | undefined;
    selectedInternetConnection?: any | null | undefined;
    dthConnection?: boolean | null | undefined;
    selectedDTHConnection?: any | null | undefined;
    noofDesktop?: number | null | undefined;
    noofLaptop?: number | null | undefined;
    noofTablet?: number | null | undefined;
    noofPrinter?: number | null | undefined;
    noofProjector?: number | null | undefined;
    noofDigiBoard?: number | null | undefined;
    //
    noofTeachersPrimary?: number | null | undefined;
    noofTeachersPrimaryandUpperPrimary?: number | null | undefined;
    noofTeachersHigerSecondaryOnly?: number | null | undefined;
    noofTeachersSecondaryandHigerSecondary?: number | null | undefined;
    noofTeachersPrePrimaryandPrimary?: number | null | undefined;
    noofTeachersUpperPrimary?: number | null | undefined;
    noofTeachersSecondaryOnly?: number | null | undefined;
    noofTeachersUpperPrimaryandSecondary?: number | null | undefined;
    noofTeachersPrePrimaryOnly?: number | null | undefined;
    noofTeachersRegular?: number | null | undefined;
    noofTeachersParttime?: number | null | undefined;
    noofTeachersContract?: number | null | undefined;
    noofTeachersMale?: number | null | undefined;
    noofTeachersFemale?: number | null | undefined;
    noofTeachersTransgender?: number | null | undefined;
    totalNoofTeachers?: number | null | undefined;
    noofTotalTeacherReceivedServiceTraining?: number | null | undefined;
    totalTeacherInvolveinNonTeachingAssignment?: number | null | undefined;
    noofTeachersBelowGraduate?: number | null | undefined;
    noofTeachersGraduate?: number | null | undefined;
    noofTeachersPostGraduateandAbove?: number | null | undefined;
    noofTotalTeachersTrainedinComputer?: number | null | undefined;
    noofTeachersAgedAbove55?: number | null | undefined;
    noofTeachersDiplomaorCertificateinbasicteacherstraining?: number | null | undefined;
    noofTeachersBachelorofElementaryEducation?: number | null | undefined;
    noofTeachersBEdorEquivalent?: number | null | undefined;
    noofTeachersMEdorEquivalent?: number | null | undefined;
    noofTeachersDiplomaorDegreeinSpecialEducation?: number | null | undefined;
    noofTeachersPursuinganyRelevantProfessionalCourse?: number | null | undefined;
    //
    isActive?: boolean | null | undefined;
    userId?: number | null | undefined;
    ipAddress?: string | null | undefined;

}





